### ISSUE TITLE
Correct processing for constructors

### ISSUE THREAD

**Issue by denis-zhdanov** [denis-zhdanov/traute#56]
There is an NPE on attempt to check if we should instrument method return type during constructors processing (resulting AST has null as a return type for constructors):

java.lang.NullPointerException
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.mayBeInstrumentReturnType(InstrumentationApplianceFinder.java:197)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.shouldInstrumentReturnExpression(InstrumentationApplianceFinder.java:112)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitMethod(InstrumentationApplianceFinder.java:89)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitMethod(InstrumentationApplianceFinder.java:28)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitClass(InstrumentationApplianceFinder.java:72)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitClass(InstrumentationApplianceFinder.java:28)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:120)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitCompilationUnit(InstrumentationApplianceFinder.java:57)
        at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitCompilationUnit(InstrumentationApplianceFinder.java:28)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
        at tech.harmonysoft.oss.traute.javac.TrauteJavacPlugin$1.finished(TrauteJavacPlugin.java:150)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
        at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
        at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:638)

**Comment by denis-zhdanov** [comment]
Fixed
