### ISSUE TITLE
Avoid NPE during processing classes from default package

### ISSUE THREAD

**Issue by denis-zhdanov** [denis-zhdanov/traute#66]
```
java.lang.NullPointerException
	at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitCompilationUnit(InstrumentationApplianceFinder.java:57)
	at tech.harmonysoft.oss.traute.javac.common.InstrumentationApplianceFinder.visitCompilationUnit(InstrumentationApplianceFinder.java:28)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
	at tech.harmonysoft.oss.traute.javac.TrauteJavacPlugin$1.finished(TrauteJavacPlugin.java:166)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:638)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:665)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:857)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

**Comment by denis-zhdanov** [comment]
Done
